### ISSUE TITLE
ez create doesn't work

### ISSUE THREAD

**Issue by stevenbustos** [ezsystems/launchpad#101]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version          | 1.8.8
| Environment      | Linux

Hi, I just installed ezlaunchpad in my Arch Linux machine, the init command works well, but when I run ~/ez clean or create it doesn't do anything, what could cause this? 
I'm running PHP 8.0.2, Docker 20.10.3 and docker-compose 1.28.2

**Comment by Plopix** [comment]
PHP 8 is not supported yet on the host.

We've got to make it work soon

**Comment by Plopix** [comment]
https://github.com/ezsystems/launchpad/pull/100 should fix it ;)

**Comment by Plopix** [comment]
fixed in v1.9.1
