### ISSUE TITLE
Incorrect env variable: symfony_tmp_dir

### ISSUE THREAD

**Issue by raupie** [ezsystems/launchpad#26]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version          | latest
| Environment      | Linux

In ez engine container, environment variable `SYMFONY_TMP_DIR` has a typo. `/tmp/ezplatormcache/var/cache/dev` 

I'm not sure if this is causing any issues with `ez sf cache:clear` by not emptying the cache folder.

I've been running bin/console inside the engine container to work around this.

**Comment by Plopix** [comment]
Hello @raupie, thank's for reporting that, What's the typo and the error you got?

**Comment by raupie** [comment]
No error when running. It's missing the 'f' in ezplatormcache in the docker-compose file. I was going crazy typing ezplatform and getting an error that the dir didn't exist. 

`- "SYMFONY_TMP_DIR=/tmp/ezplatormcache/"` -> - `"SYMFONY_TMP_DIR=/tmp/ezplatformcache/"`
