### ISSUE TITLE
clear prod cache via sf shortcut broken

### ISSUE THREAD

**Issue by raupie** [ezsystems/launchpad#27]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Version          | x.y.z
| Environment      | Linux

I can clear my cache via `ez sf cache:clear` & `ez sf cache:clear --env=dev` however when trying to clear the prod env cache I get a `[ERROR] Your are not in a folder managed by eZ Launchpad.` when running `ez sf cache:clear --env=prod`  

Not a deal breaker, I can ez enter -> cd project/ezplatform -> bin/console cache:clear --env=prod but the ez sf shortcut is supper nice to have :)

**Comment by Plopix** [comment]
hey @raupie thanks for bringing that up.

In fact you cannot pass arguments like that, you should do:

```bash
ez sf 'cache:clear --env=prod'
```
I know it is odd, but otherwise, arguments are passed to the `ez` command.

**Comment by raupie** [comment]
Thanks for tip. So anytime you are running a console command that takes extra arguments just wrap them in single quotes. Makes sense.
