### ISSUE TITLE
platform.sh deploy redis error

### ISSUE THREAD

**Issue by raupie** [ezsystems/launchpad#28]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Version          | x.y.z
| Environment      | Linux

Default deploy commands that were created by ezlaunchpad throws an error in platform.sh deploy logs.

`bin/console cache:pool:clear cache.redis` throws an error: `You have requested a non-existent service "cache.redis"

**Comment by Plopix** [comment]
I don't think that is correct right @raupie ? Redis is per default in the Platform.sh config then I don't see why it would not work. do you have more information?

**Comment by raupie** [comment]
I think this was solved with ezplatform #289 'Docker Redis Session Storage'
