### ISSUE TITLE
Install composer globally in the image

### ISSUE THREAD

**Issue by Plopix** [ezsystems/launchpad#33]
Thx @florianalexandre for the idea.

- [ ] install composer in the dockerfile
- [ ] remove the code that manages that in eZ Launchad

**Comment by raupie** [comment]
I was just looking at this. @Plopix are you going to install this in the dockerfile or in the entrypoint.bash?

**Comment by raupie** [comment]
I see it's in the dockerfile, very cool. thanks.

**Comment by Plopix** [comment]
done
