### ISSUE TITLE
[New Feature?] New commands to import storage from remote url

### ISSUE THREAD

**Issue by yhanini** [ezsystems/launchpad#38]
| Q                | A
| ---------------- | -----
| Feature request? | yes

To avoid travis error on building docker we need to have the latest database and storage.
Keep ez docker:importdata

But we could add some commands like :

- ez docker:importdb 
- ez docker:importstorage
- ez docker:import-storage-from-url
also : (but not very secure) :
- ez docker:import-db-from-url

So we could use dropbox or gdrive to import storage. What do you think  ?

**Comment by Plopix** [comment]
thx @yhanini for bringing that subject!

My feeling on that:

- Giving that now eZ 2.2+ can work with "placeholders" and storage can be dissociated from the DB. (and just not present)
- Giving then that only `db` is really what we need to share
- GIving that `ez docker:import-db-from-url` is indeed tricky in term of security and would be different for each of us I guess.

=> I think eZ Launchpad is fine with what it has right now.

I think a solution is already possible, per project:

- You can definitely do a script, put it on your project and then automate that in Travis using for instance:

`~/ez exec engine "bash project/scripts/dowhateveryouneed.bash`

And that script can do the automation you need to retrieve the DB

You see my point?

**Comment by yhanini** [comment]
Okay. I see what you mean.

Thanks
