### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by Plopix** [ezsystems/launchpad#45]
Documentation is harder to update because we did it "multilingual"

- [ ] Do you think that is useful? I could be full English and would simplify the addition etc.

- [ ] Doc for Blackfire  usage/config
- [ ] Doc for MySQL usage/config
- [ ] Doc for X-Debug  usage/config

More, other ideas for the doc?

**Comment by Heyfara** [comment]
After contributing to the doc, event for something very simple and short, I can already see an issue with a multilingual doc. I can write English and French, but not Norwegian. Depending on the contributors, one (or more) translation is inevitably going to stay behind the English one.
I'll vote for only English
