### ISSUE TITLE
Remove support for PHP5.6

### ISSUE THREAD

**Issue by Plopix** [ezsystems/launchpad#46]
What do you think @andrerom 

Do we need to provide the support for 5.6?
We are talking about the PHP version useful for the CLI of eZ Launchpad, not for eZ Platform.

Removing PHP 5.6 support would allow us to:

- move to Symfony 4.1
- use strong type hint
- speed Travis

Actually, the question is for everybody, I feel like since OSX ships 7.1 by default, we could/should.

?

**Comment by andrerom** [comment]
Makes sense for me, but maybe plan this (PHP 7.1 bump which you'll need for SF4)  as a bundle of features you intend for v2 of launchpad.

**Comment by Plopix** [comment]
will be addressed in https://github.com/ezsystems/launchpad/pull/72
