### ISSUE TITLE
composer_cache no longer writable

### ISSUE THREAD

**Issue by raupie** [ezsystems/launchpad#47]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Version          | x.y.z
| Environment      | Linux

Just noticed the composer_cache folder is no longer owned by wwwdata but by root.

**Comment by raupie** [comment]
Cannot create cache directory /var/www/composer_cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/composer_cache/files/, or directory is not writable. Proceeding without cache

Working on PR. Feedback welcome.

**Comment by xserna** [comment]
I can confirm the issue. Two days ago on a fresh install in the computer of a teammate suffered that problem.

**Comment by raupie** [comment]
Tested on existing project and from fresh ez init. Trying to install `composer require netgen/tagsbundle` throws the errors. Composer still downloads the packages however on my host machine the ~/.composer_cache has files owned by root which makes sense since composer_install.bash recipe is being run in the container with the root user and not www-data.

**Comment by raupie** [comment]
Not sure if this 100% fixes it but it worked for me with a fresh `~/ez init` 

PR: #48 

The /var/www/composer_cache/repo/https---updates.ez.no.ttl would sometimes be owned by root and cause issues. I would delete the composer_cache from my host and that would fix it.

**Comment by raupie** [comment]
Closing this. 

I believe the fix is just to manually correct permissions in the local ~/.composer outside of the docker containers.
