### ISSUE TITLE
Error on "defaults" command execution in Ubuntu

### ISSUE THREAD

**Issue by xserna** [ezsystems/launchpad#73]
This line is causing 2 issues here (Ubuntu 16.04):

- New package requirement: **gnustep-base-runtime** to have "defaults" command available
- After that installed, every launchpad execution we're getting: **defaults read: couldn't read default**

https://github.com/ezsystems/launchpad/blob/dd886451bc63cc5bf5bb5977d990d694ab86604d/src/functions.php#L46

Don't know if in modern Ubuntu releases is also happening.

Thanks!

**Comment by Plopix** [comment]
Is that an error or a warning? I can add `@` to remove that warning I guess. I will look into it. Thanks for reporting @xserna !

**Comment by xserna** [comment]
It's the output of the command, in the stderr channel:

$ defaults read loginwindow SystemVersionStampAsString
defaults read: couldn't read default

$ echo $?
2

So I believe that's an error message, I'm right?

Thanks!

—
Xavier Serna
Analyst & eZ Publish / Platform Expert
Tel. (+34) 937 26 41 99 ext. 513
www.microblau.net<https://www.microblau.net>
-----------------------
Porta al Cloud la teva empresa amb Office 365: Comunicació, col·laboració, Digital Workplace…<https://goo.gl/DsLK9x>
-----------------------

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
________________________________

**Comment by Plopix** [comment]
yes right, I was trying to identify the level of emergency on that one. If it breaks a build or something. I will fix that asap!

**Comment by xserna** [comment]
Great that you can fix it soon, for us there is no emergency, the only thing is that annoying message in console, but don't know for other people out there 🙂

Thanks!

**Comment by Plopix** [comment]
when all this is green, you can update to 1.4.5 https://travis-ci.org/ezsystems/launchpad/builds/617883047 !

I am closing! fix is here: https://github.com/ezsystems/launchpad/commit/5ad8293a2e15944bda69eb82e8daf781e02cc527

Thanks @xserna !
