### ISSUE TITLE
ERROR: Solr: invalid port specification: "65983"

### ISSUE THREAD

**Issue by iegorka** [ezsystems/launchpad#75]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version          | 1.4.5
| Environment      | Mac

It seems the limit for the TCP port prefix should be between 1 and 64.

With this option:
```
What is the TCP Port Prefix you want? [42]:
> 65
```

I had this error 
```
ERROR: for solr  Cannot create container for service solr: invalid port specification: "65983"
ERROR: Encountered errors while bringing up the project.
```

**Comment by Plopix** [comment]
That is very true ;-)

I'll do that soon
