### ISSUE TITLE
ERROR 1114 (HY000) at line 8834: The table 'xxxx' is full

### ISSUE THREAD

**Issue by pboethig** [ezsystems/launchpad#87]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Version          | x.y.z
| Environment      | Linux/Mac/Windows

If I try to import 14 GB dump i get:

ERROR 1114 (HY000) at line 8834: The table 'xxxx' is full

kind regards

Peter

**Comment by Plopix** [comment]
hello,

That's probably your docker configuration which is not allowing enough space to your container

**Comment by pboethig** [comment]
yes, indeed. It was the ressource confif in docker for mac.

thx man!
