### ISSUE TITLE
yarn watch not working

### ISSUE THREAD

**Issue by pboethig** [ezsystems/launchpad#88]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version          | x.y.z
| Environment      | Mac/Windows

If I activate yarn watch to watch filesystemchanges on css, html, js files the watcher does not react on any changes on editing files locally

how can we solve this

kind regards
Peter

**Comment by Plopix** [comment]
yes that's a Mac OS issue actually...

I have bypassed that limitation by watching from the host and not inside the container...

**Comment by pboethig** [comment]
cool. 

we have solved it this way:

module.exports = {
  //...
  watchOptions: {
    poll: 1000 // Check for changes every second
  }
};
If watching does not work for you, try out this option. Watching does not work with NFS and machines in VirtualBox.



the poll config solved it.

thx

**Comment by Plopix** [comment]
documentation added there: https://github.com/ezsystems/launchpad/pull/89
