### ISSUE TITLE
max_allowed_packet error

### ISSUE THREAD

**Issue by pboethig** [ezsystems/launchpad#91]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version          | x.y.z
| Environment      | Mac/Windows

I get a  Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet'

How can i Increese  max_allowed_packet

Kind regards

Peter

**Comment by Plopix** [comment]
Same, definitely not a "bug" (careful in the Issue creation)

That is not related to eZ Launchpad at all. See the docker configuration of the image you are using.

Thanks
