### ISSUE TITLE
Add a new command init_ibexa

### ISSUE THREAD

**Issue by ddoghri** [ezsystems/launchpad#99]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| Version                 | 3.3.x
| Environment        | Mac

Add a new  command  init_ibexa to initialize a new ibexa 3.3.x project

**Comment by Plopix** [comment]
see https://github.com/ezsystems/launchpad/pull/100

**Comment by Plopix** [comment]
fixed in v1.9.1
